#!/usr/bin/env python
# -*- coding: utf-8; tab-width: 4; -*-
#
# Copyright (C) 2016 Julian Qian
#
# @file      gen_feat_idx.py
# @author    Julian Qian <junist@gmail.com>
# @created   2016-07-22 00:58:26
#

import os
import sys


def main():
    print "// Generated by %s automatically." % os.path.abspath(sys.argv[0])
    print "#pragma once"
    print "namespace feat_idx {"
    print "enum {"
    idx = 1
    for line in sys.stdin:
        item = line.strip()
        if item.startswith("#"):
            continue
        print "  {0:<20} = {1},".format(item.upper(), idx)
        idx += 1
    print "  {0:<20} = {1}".format("MAX_NUM", idx)
    print "};"
    print "}"


if __name__ == "__main__":
    main()
