// Generated by /home/jqian/works/rank/contrib/gen_feat_idx.py automatically.
#pragma once
namespace feat_idx {
enum {
  CITY_CODE            = 1,
  HAS_DATE             = 2,
  MAX_PRICE            = 3,
  PRICE                = 4,
  DISTANCE             = 5,
  PROPORTION           = 6,
  REVIEW               = 7,
  REVIEW_CNT           = 8,
  AUTO_ACCEPT          = 9,
  QUICK_ACCEPT         = 10,
  IS_RECOMMEND         = 11,
  STATION              = 12,
  CONFIRM_RATE         = 13,
  COLLECT_COUNT        = 14,
  IS_COLLECT           = 15,
  IS_ORDERED           = 16,
  IS_MODEL             = 17,
  IS_PRICE             = 18,
  QUALITY              = 19,
  MODEL                = 20,
  MAX_NUM              = 21
};
}
