CREATE TABLE `car_rank_feats` (
  `car_id` int(11) NOT NULL,
  `score` float DEFAULT NULL COMMENT '车辆质量分',
  `w_price` float DEFAULT NULL,
  `proportion` float DEFAULT NULL COMMENT 'car_owner_price.proportion',
  `w_send` float DEFAULT NULL,
  `owner_send` tinyint(1) DEFAULT NULL,
  `owner_send_desc_len` int(11) DEFAULT NULL,
  `owner_send_has_tags` tinyint(1) DEFAULT NULL,
  `w_confirm` float DEFAULT NULL,
  `auto_accept` tinyint(1) DEFAULT NULL COMMENT '是否开启自动接单',
  `recent_rejected` int(11) DEFAULT NULL COMMENT '最近10个单里的拒单数',
  `recent_accepted` int(11) DEFAULT NULL COMMENT '最近10个单里的接单数',
  `w_review_owner` float DEFAULT NULL,
  `review_owner` float DEFAULT NULL COMMENT '3个月内最近10个订单对车主的评价分均分',
  `w_review_car` float DEFAULT NULL,
  `review_car` float DEFAULT NULL COMMENT '3个月内最近10个订单对车辆的评价分均分',
  `recommend_level` smallint(4) DEFAULT NULL,
  `manual_weight` int(11) DEFAULT NULL,
  `pic_num` int(11) DEFAULT NULL,
  `desc_len` int(11) DEFAULT NULL,
  `recent_cancelled_owner` int(11) DEFAULT NULL COMMENT '最近一个月内车主取消订单数',
  `recent_cancelled_renter` int(11) DEFAULT NULL COMMENT '1个月内最后10个支付后订单(不包含接收后订单)租客取消数',
  `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`car_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
