DROP TABLE IF EXISTS `car_rank_feats`;
CREATE TABLE `car_rank_feats` (
  `car_id` int(11) unsigned NOT NULL,
  `city_code` varchar(6) DEFAULT NULL,
  `price_daily` int(11) DEFAULT '0' COMMENT '车辆当前日租价',
  `model` int(11) DEFAULT '0' COMMENT '车辆类型',
  `suggest_price` float DEFAULT '0' COMMENT '基准价',
  `proportion` float DEFAULT '0' COMMENT 'car_owner_price.proportion',
  `price_tuning` float DEFAULT '0' COMMENT 'price_tools_rank.score',
  `owner_send` tinyint(1) DEFAULT '0' COMMENT 'car_rank.owner_can_send',
  `owner_send_desc_len` int(11) unsigned DEFAULT '0' COMMENT '车主送车上门描述字符数',
  `owner_send_distance` int(11) unsigned DEFAULT '0' COMMENT '车主送车上门距离',
  `owner_send_has_tags` tinyint(1) DEFAULT '0' COMMENT '租客评价里有送车上门标签',
  `auto_accept` tinyint(1) DEFAULT '0' COMMENT '是否开启自动接单',
  `quick_accept` tinyint(1) DEFAULT '0' COMMENT '是否开启闪接',
  `recent_rejected` int(11) DEFAULT '0' COMMENT '最近10个单里的拒单数',
  `recent_accepted` int(11) DEFAULT '0' COMMENT '最近10个单里的接单数',
  `recent_paid` int(11) DEFAULT '0' COMMENT '最近支付订单数',
  `recent_paid1` int(11) DEFAULT '0' COMMENT '最近支付订单数1',
  `recent_paid2` int(11) DEFAULT '0' COMMENT '最近支付订单数2',
  `recent_completed` int(11) DEFAULT '0' COMMENT '最近完成订单数',
  `recent_completed1` int(11) DEFAULT '0' COMMENT '最近完成订单数1',
  `recent_completed2` int(11) DEFAULT '0' COMMENT '最近完成订单数2',
  `review_owner` float DEFAULT '0' COMMENT '3个月内最近10个订单对车主的评价分均分',
  `review_car` float DEFAULT '0' COMMENT '3个月内最近10个订单对车辆的评价分均分',
  `review_cnt` int(11) DEFAULT '0' COMMENT '评价数',
  `review` float DEFAULT '0' COMMENT '评价分均分 car_stats.review',
  `confirm_rate` float DEFAULT '0' COMMENT '接单率 car_stats.confirmed_rate_app',
  `collect_cnt` int(11) DEFAULT '0' COMMENT '收藏数 car_collect',
  `recommend_level` smallint(4) DEFAULT '0' COMMENT '车辆推荐等级 car_rank.recommend_level',
  `pic_num` int(11) unsigned DEFAULT '0' COMMENT '车辆图片数',
  `desc_len` int(11) unsigned DEFAULT '0' COMMENT '车辆描述字符数',
  `recent_cancelled_owner` int(11) DEFAULT '0' COMMENT '最近一个月内车主取消订单数',
  `recent_paid_cancelled_owner` int(11) DEFAULT '0' COMMENT '最近一个月内车主取消支付后订单车主取消数',
  `recent_cancelled_renter` int(11) DEFAULT '0' COMMENT '1个月内最后10个支付后订单租客取消数',
  `verified_time` datetime DEFAULT NULL COMMENT 'car.cs_verify>0 -> car.verified_time',
  `available_days` int(11) DEFAULT '0' COMMENT '最近一个月内可见可租天数',
  `rented_days` int(11) DEFAULT '0' COMMENT '最近出租天数',
  `station` int(11) DEFAULT '0' COMMENT '地铁站id',
  `sales_discount` tinyint(1) DEFAULT '0' COMMENT '满车日打折',
  `sales_vip` tinyint(1) DEFAULT '0' COMMENT 'VIP折扣',
  `sales_new` tinyint(1) DEFAULT '0' COMMENT '首单8折',
  `manual_weight` int(11) DEFAULT '0' COMMENT '运营人工权重',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`car_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
